// <auto-generated />
using System;
using CDNAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CDNAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20241130235723_Adding AgoraLog")]
    partial class AddingAgoraLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CDNAPI.Models.AgoraLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("MinhaCDNLogId");

                    b.Property<string>("cachestatus");

                    b.Property<string>("clientId");

                    b.Property<string>("httpmethod");

                    b.Property<string>("provider");

                    b.Property<string>("statuscode");

                    b.Property<string>("timetaken");

                    b.Property<string>("uripath");

                    b.HasKey("Id");

                    b.HasIndex("MinhaCDNLogId");

                    b.ToTable("AgoraLogs");
                });

            modelBuilder.Entity("CDNAPI.Models.MinhaCDNLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cachestatus");

                    b.Property<string>("clientId");

                    b.Property<string>("httpmethod");

                    b.Property<string>("provider");

                    b.Property<string>("statuscode");

                    b.Property<string>("timetaken");

                    b.Property<string>("uripath");

                    b.HasKey("Id");

                    b.ToTable("MinhaCDNLogs");
                });

            modelBuilder.Entity("CDNAPI.Models.AgoraLog", b =>
                {
                    b.HasOne("CDNAPI.Models.MinhaCDNLog", "MinhaCDNLog")
                        .WithMany()
                        .HasForeignKey("MinhaCDNLogId");
                });
#pragma warning restore 612, 618
        }
    }
}
