// <auto-generated />
using System;
using CDNAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CDNAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CDNAPI.Model.MinhaCDNLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cachestatus");

                    b.Property<string>("clientId");

                    b.Property<string>("httpmethod");

                    b.Property<string>("provider");

                    b.Property<string>("statuscode");

                    b.Property<string>("timetaken");

                    b.Property<string>("uripath");

                    b.HasKey("Id");

                    b.ToTable("MinhaCDNLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
